config/routes.rb
NewsRoom::Application.routes.draw do
 
  resources :areas

  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"

  get "sign_up" => "users#new", :as => "sign_up"
  get "glutton/store" => "articles#fetch_and_store", :as => "store_glutton_feeds"
  get "feeds_processor/process" => "articles#process_feeds", :as => "process_feeds"
  get "non_published" => "articles#show_non_published", :as => "non_published"
  get "articles/non_published" => "articles#show_non_published", :as => "non_published_articles"
  get "articles/chief_editors" => "articles#chief_editors_non_published", :as => "chief_editors"
  get "articles/chief_editors_country" => "articles#chief_editors_country_non_published", :as => "chief_editors_country"
  root :to => "articles#index"
  
  get "errors/overload" => "errors#overload"
  get 'mu-a8f5303e-aa326727-78ec284a-3daa78fb' => "errors#error"

  match "articles/:id/upgrade" => "articles#up_editor_grade"
  match "articles/create_random" => "articles#create_random"

  resources :users
  resources :sessions
  resources :news_agencies
  resources :articles
  

end

app/models/article.rb
class Article
  include Mongoid::Document
  include Mongoid::MultiParameterAttributes

  field :headline,      type: String
  field :deck,          type: String
  field :story,         type: String
  field :published_on,  type: Date
  field :guid,          type: String
  field :url,           type: String
  field :is_published,  type: Boolean
  #field :categories,    type: Array
  field :country,       type: String
  
  field :grade, type: Float
  field :editors_grade, type: Integer
  field :chief_editor_grade, type: Integer
  field :chief_editor_country_grade, type: Integer   #xq integer? si son varias notas!


  belongs_to :news_agency
  belongs_to :user
  belongs_to :area #seccion

  has_many :article_categories
  has_many :categories, through: :article_categories

  embeds_many :pictures

  before_save :categorize
  before_save :not_published
  before_save :add_country
  after_create :create_guid

  scope :published, -> { where(is_published: true) }
  scope :nonpublished, -> { where(is_published: false) }

  validates_presence_of :headline, message: "Headline must be present"

  PUBLISH_GRADE = 15

  #paginate(:page => params[:page], :per_page => 30)
  def self.paginated(page_num, per_page=5)
    page(page_num).per(per_page)
  end
  
  def not_published
    unless is_published
      self.is_published = false      
    end
    true   #it does not prevent the object being saved
  end

  def self.by_area(area)
    unless area.blank?
      where(area: area)      
    else
      scoped
    end
  end
  def self.by_country(country)
    unless country.blank?
      where(country: country)
    else
      scoped
    end
  end
  def self.by_area_and_country(user)
    if user
      by_country(user.country).by_area(user.area)      
    else
      scoped
    end
  end

  def add_grade
  	#self.grade = self.grade || 0 
    self.grade  = self.editors_grade || 0 #if editors_grade
  	self.grade += 3 * (self.chief_editor_grade || 0) #if chief_editor_grade
  	self.grade += 3 * (self.chief_editor_country_grade || 0) #if self.chief_editor_country_grade
    will_remove_cache = false
    if self.grade.to_i >= Article::PUBLISH_GRADE
      self.is_published = true
      #kills the page cache
      #remove_cache
      will_remove_cache = true
    end
  	self.save
    will_remove_cache
  end

  def user_name
    if user
      return user.name
    else
      return ""
    end
  end

  def categorize
    if available_category_names
      category_names.each do |c|
        ArticleCategory.construct(self, c)
      end
    end
  end
  def category_names=(array)
    @category_names = array
  end
  def category_names
    @category_names
  end

  def available_category_names
    return false if @category_names.nil?
    return false if !(@category_names.class.eql?(Array))
    return false if @category_names.empty?
    return true
  end

  def add_country
    if self.country.blank?
      self.country = "Chile"
    end
  end
  def create_guid
    if self.guid.blank?
      self.guid = self._id.to_s
      self.save
    end
  end

  def set_initial_grades
    self.grade = 0
    self.editors_grade = 0
    self.chief_editor_grade = 0
    self.chief_editor_country_grade = 0
  end

  def picture_name
    if self.pictures.any?
      self.pictures.first.name 
    else
      ""
    end
  end

  def add_picture( image_params )
    self.pictures.create(image_params) if image_params
  end

  def get_category_names
    array = []
    if self.article_categories
      self.article_categories.each do |c|
        array.append(c.category.name)
      end
    end
    array.join(',')
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  #skip_authorization_check
  #caches_page :index , :expires_in => 7.seconds 
  #caches_page :index 
  #expire_page "/?page=2"
  #caches_action :index
  # GET /articles
  # GET /articles.json
  load_and_authorize_resource
  #skip_before_filter :verify_authenticity_token, :only => [:update,:create]
  def index
    #remove_cache #if params[:page]
    #@articles = #Article.where(:is_published => true)
    @articles = Article.published.paginated(params[:page], 10)
    respond_to do |format|

      format.html # index.html.erb
      format.json { render json: @articles }
    end
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @article = Article.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/new
  # GET /articles/new.json
  def new
    @article = Article.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/1/edit
  def edit
    @article = Article.find(params[:id])
    
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(params[:article])
    @article.set_initial_grades
    if current_role.include?('journalist')
      @article.user = current_user
      @article.country = current_user.country
    end
    respond_to do |format|
      if @article.save
        @article.add_picture(params[:picture])
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render json: @article, status: :created, location: @article }
      else
        format.html { render action: "new" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /articles/1
  # PUT /articles/1.json
  def update
    @article = Article.find(params[:id])
    if params[:tags]
      @article.category_names=(params[:tags].split(","))
      ArticleCategory.where(:article_id => @article.id).destroy_all
    end
    respond_to do |format|
      if @article.update_attributes(params[:article])

        if(current_role.include?('editor') || current_role.include?('chief_editor') || current_role.include?('chief_editor_country'))
          remove = @article.add_grade
          if remove
            remove_cache
          end
        end

        format.html { redirect_to :back, notice: 'Article was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end

    end
  end
  def up_editor_grade
    @article = Article.find(params[:id])
    @article.editors_grade += 1
    respond_to do |format|
      if @article.save
        format.html { redirect_to articles_path, notice: 'Article was successfully upgraded.' }
        format.json { head :no_content }
      else 
        format.html { redirect_to articles_path, notice: 'Article was not successfully upgraded.' }
        format.json { head :no_content }  
      end
    end
  end
  def create_random
    random = BCrypt::Engine.generate_salt
    Article.create(headline: "random#{random}")
    respond_to do |format|
      format.html { redirect_to articles_path, notice: 'Article was successfully created at random.' }
      format.json { head :no_content }
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url }
      format.json { head :no_content }
    end
  end

  def fetch_and_store
    Glutton.fetch_and_store
    redirect_to articles_path, notice: "New feeds were fetched and processed"
  end
  def process_feeds
    FeedProcessor.process_feeds
    redirect_to articles_path, notice: "New feeds were processed"
  end
  
  def show_non_published
    if current_user
      @articles = Article.where(:is_published => false, :editors_grade =>0)#, :country => current_user_country, :area => current_user_area) #, :user_id.ne => current_user_id
    else
      @articles = Article.where(:is_published => false, :editors_grade =>0) #, :user_id.ne => current_user_id
    end
    @news = Article.nonpublished.where(:area.exists => false).limit(5)
    @country = current_user_country

    respond_to do |format|
      format.html
      format.json { render json: @articles }
    end
  end

  def chief_editors_non_published
    if current_user && current_role.include?('chief_editor')
      @articles = Article.where(:is_published => false, :chief_editor_grade =>0, :editors_grade.gt => 0) #, :country => current_user_country, :area => current_user_area) #, :user_id.ne => current_user_id
    else
      redirect_to articles_path, notice: "No tienes los permisos necesarios"
      return
      #@articles = Article.where(:is_published => false, :chief_editor_grade =>0) #, :user_id.ne => current_user_id
    end

    respond_to do |format|
      format.html { render :template => "articles/show_non_published" }
      format.json { render json: @articles }
    end
  end

  def chief_editors_country_non_published
    if current_user && current_role.include?('chief_editor_country')
      @articles = Article.nonpublished.where(:chief_editor_country_grade =>0, :editors_grade.ne =>0, :chief_editor_grade.ne =>0,:user_id.ne => current_user_id, :country => current_user_country)
    else
      redirect_to articles_path, notice: "No tienes los permisos necesarios"
      return
    end
    
    respond_to do |format|
      format.html { render :template => "articles/show_non_published" } 
      format.json { render json: @articles }
    end
  end


end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.erb
<!-- <% cache article do %> -->
	<h3><%= link_to article.headline, article %></h3>
	<p><%= simple_format article.deck %></p>
<!-- <% end %>-->

app/views/articles/_form.html.erb
<%= form_for @article, :validate => true, :html => {:multipart => true}  do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if @article.new_record? %>
    <div class="field">
      <%= f.label :published_on %><br />
      <%= f.date_select :published_on %>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :headline %><br />
    <%= f.text_field :headline %>
  </div>
  <div class="field">
    <%= f.label :deck %><br />
    <%= f.text_field :deck %>
  </div>
  <div class="field">
    <%= f.label :story %><br />
    <%= f.text_area :story %>
  </div>


  <div class="field">
    <%= f.label :news_agency_id %><br />
    <%= f.collection_select :news_agency_id, NewsAgency.all, :id, :name, { :include_blank => "Select Agency" } %>
  </div>

   <!-- <div class="field">
      <%= f.label :grade %><br />
      <%= f.text_field :grade %>
    </div>
-->

  <div class="field">
      <%= f.label :area_id %><br />
      <%= f.collection_select :area_id, Area.all, :id, :name, {:include_blank => "Select Area"}%>
  </div>

  <div class="field">
    <%= f.label :tags %><br />
    <%= text_area_tag  :tags , @article.get_category_names %>
  </div>

  <div class="field">
    <%= f.label :country %>
    <%= select(:article, :country, User::COUNTRY) %>
  </div>

  <%= render :partial => 'grades', :locals =>{:f => f} %>

  <div class="field">
    <%= f.fields_for :pictures do |f| %>
      <%= render "picture_fields", :f => f %>
    <% end %>
  </div>

  <div class="actions">
    <%= f.submit "Update Article", :class => "create_article" %>
  </div>
<% end %>

app/views/articles/_grade_form.html.erb
<%= form_for article, :remote => false  do |f| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>
      <ul>
        <% article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= render :partial => 'grades', :locals =>{:f => f} %>

  <div class="actions">
    <%= f.submit "Grade Article", :class => "create_article" %>
  </div>
<% end %>

app/views/articles/_grades.html.erb
<% if current_role.include?("editor") and f.object.editors_grade == 0 %>
  <div class="field">
      <%= f.label :editors_grade %><br />
      <%= f.text_field :editors_grade %>
    </div>
<% elsif current_role.include?("chief_editor") and f.object.chief_editor_grade == 0 %>
  <div class="field">
      <%= f.label :chief_editor_grade %><br />
      <%= f.text_field :chief_editor_grade %>
    </div>
<% else #if current_role.include?("chief_editor_country") %>
  <div class="field">
      <%= f.label :chief_editor_country_grade %><br />
      <%= f.text_field :chief_editor_country_grade %>
    </div>
<% end %>

app/views/articles/_picture_fields.html.erb
  <%= f.label :image, "Upload a picture:" %>
  <%= f.file_field :image, name: "picture[image]" %>

  <!-- f.file_field :image, multiple: true, name: "picture[image]" -->

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>NewsRoom</h1>
<h2> Noticias principales </h2>
<div class="row">
  <div class="span8 offset2">
    <% @articles.each do |article| %>
      <div class="well">
        <%= render article %>
      </div>
    <% end %>
    <%= paginate @articles, :window => 2 %>
  </div>
</div>


<% if can? :create, Article %>
<%= link_to 'New Article', new_article_path %>
<%= link_to "Populate by glutton", store_glutton_feeds_path %>
<% end %>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= form_for @article, :validate => true, :html => {:multipart => true}  do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if @article.new_record? %>
    <div class="field">
      <%= f.label :published_on %><br />
      <%= f.date_select :published_on %>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :headline %><br />
    <%= f.text_field :headline %>
  </div>
  <div class="field">
    <%= f.label :deck %><br />
    <%= f.text_field :deck %>
  </div>
  <div class="field">
    <%= f.label :story %><br />
    <%= f.text_area :story %>
  </div>


  <div class="field">
    <%= f.label :news_agency_id %><br />
    <%= f.collection_select :news_agency_id, NewsAgency.all, :id, :name, options: { include_blank: true, prompt: 'Select Person' } %>
  </div>


  <div class="field">
    <%= f.fields_for :pictures do |f| %>
      <%= render "picture_fields", :f => f %>
    <% end %>
  </div>

  <div class="actions">
    <%= f.submit "Create Article", :class => "create_article" %>
  </div>
<% end %>


<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>
<div class="span12">
<h1><%= @article.headline %></h1>
 <%= @article.published_on %>

<b><%= @article.user_name %></b>
</div>

<div class="span4">
  <% if @article.picture_name!= "" %>
    <%= image_tag(@article.picture_name) %>
  <% else %>
    <img src="http://placehold.it/350x250"></img>
  <%end%>
</div>
<div class="span8">
<p><%= simple_format @article.deck %></p>
<p> <%= @article.story %> </p>

  <p>
    <b>Grade:</b>
    <%= @article.grade %>
  </p>

  <p>
   <%= @article.news_agency.name if @article.news_agency%>
  </p>

  <p><%= @article.get_category_names %></p>


<% if can? :update, @article %>
	<%= link_to 'Edit', edit_article_path(@article) %> |
<% end %>
<%= link_to 'Back', articles_path %>
</div>

app/views/articles/show_non_published.html.erb
<h1>NewsRoom</h1>
<% if @country %>
	<h2> Noticias por aceptar en <%= @country %></h2>
<% else %>
	<h2> Noticias por aceptar</h2>
<% end %>
<div class="row">
  <div class="span8 offset2">
    <% @articles.each do |article| %>
    <div class="well">
      <h3><%= link_to article.headline, article %></h3>
      <p><%= simple_format article.deck %></p>
      <%= render "articles/grade_form", :article => article %>
    </div>
    <% end %>
  </div>
</div>
<% if @news %>
	<h2> Noticias por clasificar </h2>
	<div class="row">
	  <div class="span8 offset2">
	    <% @news.each do |news| %>
	    <div class="well">
	      <h3><%= link_to news.headline, news %></h3>
	      <p><%= simple_format news.deck %></p>
	    </div>
	    <% end %>
	  </div>
	</div>
<% end %>