config/routes.rb
NewsRoom::Application.routes.draw do
 
  resources :areas

  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"

  get "sign_up" => "users#new", :as => "sign_up"
  get "glutton/store" => "articles#fetch_and_store", :as => "store_glutton_feeds"
  get "feeds_processor/process" => "articles#process_feeds", :as => "process_feeds"
  get "non_published" => "articles#show_non_published", :as => "non_published"
  get "articles/non_published" => "articles#show_non_published", :as => "non_published_articles"
  get "articles/chief_editors" => "articles#chief_editors_non_published", :as => "chief_editors"
  get "articles/chief_editors_country" => "articles#chief_editors_country_non_published", :as => "chief_editors_country"
  root :to => "articles#index"
  
  get "errors/overload" => "errors#overload"
  get 'mu-a8f5303e-aa326727-78ec284a-3daa78fb' => "errors#error"

  match "articles/:id/upgrade" => "articles#up_editor_grade"
  match "articles/create_random" => "articles#create_random"

  resources :users
  resources :sessions
  resources :news_agencies
  resources :articles
  

end

app/models/area.rb
class Area
  include Mongoid::Document
  field :name, :type => String
  
  has_many :user
  has_many :article
  
  
  validates_presence_of :name, message: "Name must be present"
  validates_uniqueness_of :name, message: "is already taken"
end

app/controllers/areas_controller.rb
class AreasController < ApplicationController
  # GET /areas
  # GET /areas.json
   load_and_authorize_resource
  def index
    @areas = Area.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @areas }
    end
  end

  # GET /areas/1
  # GET /areas/1.json
  def show
    @area = Area.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @area }
    end
  end

  # GET /areas/new
  # GET /areas/new.json
  def new
    @area = Area.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @area }
    end
  end

  # GET /areas/1/edit
  def edit
    @area = Area.find(params[:id])
  end

  # POST /areas
  # POST /areas.json
  def create
    @area = Area.new(params[:area])

    respond_to do |format|
      if @area.save
        format.html { redirect_to @area, notice: 'Area was successfully created.' }
        format.json { render json: @area, status: :created, location: @area }
      else
        format.html { render action: "new" }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /areas/1
  # PUT /areas/1.json
  def update
    @area = Area.find(params[:id])

    respond_to do |format|
      if @area.update_attributes(params[:area])
        format.html { redirect_to @area, notice: 'Area was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /areas/1
  # DELETE /areas/1.json
  def destroy
    @area = Area.find(params[:id])
    @area.destroy

    respond_to do |format|
      format.html { redirect_to areas_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/views/areas/_form.html.erb
<%= form_for(@area) do |f| %>
  <% if @area.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@area.errors.count, "error") %> prohibited this area from being saved:</h2>

      <ul>
      <% @area.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/areas/edit.html.erb
<h1>Editing area</h1>

<%= render 'form' %>

<%= link_to 'Show', @area %> |
<%= link_to 'Back', areas_path %>

app/views/areas/index.html.erb
<h1>Listing areas</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @areas.each do |area| %>
  <tr>
    <td><%= area.name %></td>
    <td><%= link_to 'Show', area %></td>
    <td><%= link_to 'Edit', edit_area_path(area) %></td>
    <td><%= link_to 'Destroy', area, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Area', new_area_path %>

app/views/areas/new.html.erb
<h1>New area</h1>

<%= render 'form' %>

<%= link_to 'Back', areas_path %>

app/views/areas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @area.name %>
</p>


<%= link_to 'Edit', edit_area_path(@area) %> |
<%= link_to 'Back', areas_path %>