config/routes.rb
NewsRoom::Application.routes.draw do
 
  resources :areas

  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"

  get "sign_up" => "users#new", :as => "sign_up"
  get "glutton/store" => "articles#fetch_and_store", :as => "store_glutton_feeds"
  get "feeds_processor/process" => "articles#process_feeds", :as => "process_feeds"
  get "non_published" => "articles#show_non_published", :as => "non_published"
  get "articles/non_published" => "articles#show_non_published", :as => "non_published_articles"
  get "articles/chief_editors" => "articles#chief_editors_non_published", :as => "chief_editors"
  get "articles/chief_editors_country" => "articles#chief_editors_country_non_published", :as => "chief_editors_country"
  root :to => "articles#index"
  
  get "errors/overload" => "errors#overload"
  get 'mu-a8f5303e-aa326727-78ec284a-3daa78fb' => "errors#error"

  match "articles/:id/upgrade" => "articles#up_editor_grade"
  match "articles/create_random" => "articles#create_random"

  resources :users
  resources :sessions
  resources :news_agencies
  resources :articles
  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <% cache "files" do %>
  <title>NewsRoom</title>
    <link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.2.1/css/bootstrap.min.css" rel="stylesheet">
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  <% end %>
</head>
<body>

<div id="user-nav">

  <% if current_user %>

    <i class="icon-user"></i> <%= current_user.email %> |
    <%= link_to articles_path do%> <i class="icon-home"></i> <% end%>  |
    <%= link_to log_out_path do%>  <i class="icon-off"></i> <%end%>

    <% roles = Ability.get_permissions(current_user.role) %>

    <ul class="nav nav-pills pull-right">
      <% if roles.include?"admin" %>
        <li><%= link_to "News Agencies", news_agencies_path %></li>
        <li><%= link_to "User Manager", users_path %></li>
      <% end %>
        <% if roles.include?"admin" or roles.include?"editor" %>
      	<li><%= link_to "Editor Evaluation", non_published_path %></li>
      <% end %>
      <% if roles.include?"admin" or roles.include?"chief_editor" %>
        <li><%= link_to "Chief Editor Evaluation", chief_editors_path %></li>
      <% end %>
      <% if roles.include?"admin" %>
        <li><%= link_to "Areas", areas_path %>
      <% end %>
      <% if roles.include?"admin" or roles.include?"chief_editor_country" %>
        <li><%= link_to "Chief Country Editor Evaluation", chief_editors_country_path %></li>
      <% end %>
      
    </ul>
  </div>

  <% else %>
    <%= link_to "Sign up", sign_up_path %> | 
    <%= link_to "Log in", log_in_path %>
  
  <% end %>
</div>

<div class="span12">
  <% flash.each do |name, msg| %>
    <div class="alert <%= bootstrap_class_for(name) %> fade in">
    <%= content_tag :div, msg, :id => "flash#{name}" %>
    <% end %>
  </div>
</div>

<div class="container">
  <%= yield %>
</div>

</body>
</html>